### ISSUE TITLE
New release v4

### ISSUE THREAD

**Issue by naveenb30** [kciter/aws-ecr-action#31]
@kciter : Could you please create latest release version since `set_ecr_policy` is fixed here: https://github.com/kciter/aws-ecr-action/commit/034328f198022c55596bf0dfef5befbdba5043b6 ?

**Comment by kciter** [comment]
Release from 79255b7
https://github.com/kciter/aws-ecr-action/releases/tag/v4

**Comment by naveenb30** [comment]
Thanks for quick response !!
