### ISSUE TITLE
Release Version for GitHub Actions Upgrade?

### ISSUE THREAD

**Issue by KyleBrown-804** [kciter/aws-ecr-action#49]
Just wondering if there are any plans to create a release version which includes the recent GitHub Action deprecation upgrades? https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ 

I see the fix for deprecation warnings merged in here: https://github.com/kciter/aws-ecr-action/pull/46 but this is only on master at the moment and not in the last v4 release.

**Comment by michael-hanslo-paystack** [comment]
Until v5 is released, you can remove your deprecation logs by referencing the master branch directly:
`kciter/aws-ecr-action@master`

**Comment by KyleBrown-804** [comment]
Thanks, realized after that I could just target @master or even a specific commit such as the deprecation warning fix 👍

**Comment by kciter** [comment]
https://github.com/kciter/aws-ecr-action/pull/54

I've just released v5.
