### ISSUE TITLE
Path parameter not working properly

### ISSUE THREAD

**Issue by yanmendes** [kciter/aws-ecr-action#8]
# Bug report

I'm running the action with the following parameters and folder structure. Given the specs and the CircleCI orb ref, I expected that it would grab the Dockerfile from the specified path, however it's using the one at the root level, as shown in the output.

```
  uses: kciter/aws-ecr-action@v1
  with:
    account_id: ***
    access_key_id: ***
    secret_access_key: ***
    region: ***
    create_repo: true
    path: ./infra/modules/ec2/docker/nginx
    repo: blog-web-server/nginx
    tags: latest
    dockerfile: Dockerfile

├── Dockerfile
├── infra
|   ├── modules
│   |   ├── ec2
│   │   |   |   ├── docker
│   │   │   |   |   ├── nginx
│   │   │   |   |   |   ├── Dockerfile
```

## infra/modules/ec2/docker/nginx/Dockerfile
```
FROM nginx:1.19
...
```

## ~/Dockerfile
```
FROM node:10
...
```

## Action output:
```
...
== START DOCKERIZE
Sending build context to Docker daemon  14.91kB

COPY failed: no source files were specified
Step 1/5 : FROM node:10
 ---> e7671d9424c2
```

**Comment by kciter** [comment]
Here is the solution.
https://github.com/kciter/aws-ecr-action/issues/2#issuecomment-607532728

But, this has confused many people, so I'll fix it later.
